vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        marques:
                uri_prefix: /images/logos
                upload_destination: '%kernel.project_dir%/public/images/logos'
                namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        voitures:
            uri_prefix: /images/voitures
            upload_destination: '%kernel.project_dir%/public/images/voitures'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        partials:
            uri_prefix: /images/partials
            upload_destination: '%kernel.project_dir%/public/images/partials'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer